# Oh-my-zsh Stuff
export ZSH="/home/amin/.oh-my-zsh"
ZSH_THEME="dstufft"
DISABLE_MAGIC_FUNCTIONS="true"
plugins=(
  git
  docker
  fzf
  direnv
)
export EDITOR=vim
source $ZSH/oh-my-zsh.sh

# Aliases
source $HOME/.personal

# SSH Stuff 
# https://stackoverflow.com/questions/18880024/start-ssh-agent-on-login
SSH_ENV="$HOME/.ssh/agent-environment"
# Wait up to 2 seconds for the socket to appear
for i in {1..10}; do
  if [ -S "$XDG_RUNTIME_DIR/ssh-agent.socket" ]; then
    export SSH_AUTH_SOCK="$XDG_RUNTIME_DIR/ssh-agent.socket"
    break
  fi
  sleep 0.2
done

# Adding $HOME/.local/bin to $PATH
export PATH="$HOME/.local/bin:$PATH"
